CONTRIBUTING.md
README.md
docs/dataflow_processing.md
docs/milestones/E1_MS99_others.md
docs/milestones/E2_MS99_others.md

README.md was adapted to feature a more technical writing style, by reducing "you", "your", "you'll", removing ellipsis ..., remove unnecesarry words and senteces without meaning.
The section about data verticles was re-written and extended with an own document describing how dataflow is handled in NeonBee.
Two new roadmap items were added.

docs: adapt more technical writing in README, add dataflow and roadmap items

---

.github/workflows/.commitlintrc.json
src/main/java/io/neonbee/internal/processor/CountEntityCollectionProcessor.java
src/main/java/io/neonbee/internal/processor/odata/EntityExpander.java
src/test/java/io/neonbee/test/base/ODataRequest.java
src/test/java/io/neonbee/test/base/ODataRequestTest.java
src/test/java/io/neonbee/test/endpoint/odata/ODataExpandEntityCollectionTest.java
src/test/java/io/neonbee/test/endpoint/odata/verticle/NavPropsCategoriesEntityVerticle.java
src/test/java/io/neonbee/test/endpoint/odata/verticle/NavPropsProductsEntityVerticle.java
src/test/resources/io/neonbee/test/endpoint/odata/verticle/NavigationProperty.cds
src/test/resources/io/neonbee/test/endpoint/odata/verticle/NavigationProperty.csn
src/test/resources/io/neonbee/test/endpoint/odata/verticle/io.neonbee.test.NavProbs.edmx

This is a limited implementation of the $expand option. It has the
following limitations:
- Only work for read requests
- Only work for attributes of the requested entity
- No support for filter options based on attributes of expanded entities
[1] http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752359

feat: add $expand support for entity collections

---

.gitignore
.reuse/dep5
build.gradle
gradle/distribution.gradle
gradle/publishing.gradle
publishToMaven.sh
src/test/java/io/neonbee/hook/internal/HookClassTemplate.java
src/test/java/io/neonbee/internal/BasicJar.java
src/test/java/io/neonbee/internal/ClassTemplate.java
src/test/java/io/neonbee/internal/NeonBeeModuleJar.java
src/test/java/io/neonbee/test/base/NeonBeeTestBase.java
src/test/java/io/neonbee/test/helper/MockitoHelper.java
src/test/java/io/neonbee/test/helper/ReflectionHelper.java
src/test/java/io/neonbee/test/helper/ResourceHelper.java
src/test/java/io/neonbee/test/helper/WorkingDirectoryBuilder.java

This patch ...
* ... adds meta information for license, scm or developers to the
pom.xml which is required by maven central.
* adds a task to create a test Javadoc artifact, which is required by
maven central.
* adds fixes for violations in the test Javadoc
* adds the script 'publishToMaven.sh' which can be used to add required
credentials when publishing to maven central.

build: add required configuration for publishing to maven central

---

.github/workflows/.commitlintrc.json
.github/workflows/publish.yml
.reuse/dep5
build.gradle
docs/github_releases.md
gradle/changelog.gradle
gradle/publishing.gradle
gradle/release.sh

This change adds a GitHub Actions workflow which automates the
publishing of releases to maven central and the creation of GitHub
releases.

Add publishing workflow

---

gradle/release.sh

The regex pattern which was used in the sed command did not work when
running on linux.

fix: use gradle task for setting new version

---

.github/workflows/voter.yml

When pull requests are opened from a branch that sits on a fork,
the sonarqube task fails. Therefore, disabling the sonarqube task for
forks in the CI.

ci(actions): disable sonarqube on forks

---

resources/config/logback.xml
src/test/resources/io/neonbee/test/base/NeonBeeTestBase-Logback.xml

The default configuration for logback currently is using blocking appenders which, in Vert.x, is generally discouraged. Switching to logbacks AsyncAppender interface, for unblocking the logging threads.

fix: switch to async. log appender

---

src/main/java/io/neonbee/internal/processor/odata/NavigationPropertyHelper.java

This is required if the related EntityVerticle is serving multiple
entities and needs to decide which type should be returned. This is a
workaround until inter-verticle entity exchange [1] has been improved.
[1] https://github.com/SAP/neonbee/blob/main/docs/milestones/E1_MS02_entity_exchange.md

fix: add fake URI path to navigation properties requests

---

src/main/java/io/neonbee/entity/EntityVerticle.java
src/test/java/io/neonbee/entity/EntityVerticleTest.java

Before this patch it was not possible to parse OData URIs that were
containing a property as last segment of the path.

fix: enable parseUriInfo for OData URIs containing properties

---

src/main/java/io/neonbee/internal/processor/CountEntityCollectionProcessor.java
src/test/java/io/neonbee/test/endpoint/odata/ODataReadEntitiesTest.java

Mistakenly it was assumed that also filters are ignored when calculating
the system query count.

fix: calculation of system query count

---

.github/workflows/.commitlintrc.json

Allowing pascal-case in the scope for the sake of setting Java classes
as scope of the commit message.

build(commitlint): allow pascal-case scopes

---

src/main/java/io/neonbee/Launcher.java
src/test/java/io/neonbee/LauncherTest.java
src/test/java/io/neonbee/test/helper/SystemHelper.java

For deployment on cloud environments, it is beneficial to provide the
launcher options via environment variables instead of command line
arguments. This change supports reading options either from command line
or environment variable.

Make neonbee launcher options configurable via environment variables

---

build.gradle

cds4j-core is a dependency of cds-services-impl, but in NeonBee only
functionality from cds4j-core is used. With refining this dependency it
is possible to save ~1 MB of unnecessary dependencies.

build(deps): replace cds-services-impl with cds4j-core

---

resources/config/io.neonbee.internal.verticle.ServerVerticle.example.yaml
src/main/java/io/neonbee/internal/handler/DefaultErrorHandler.java
src/main/java/io/neonbee/internal/verticle/ServerVerticle.java
src/test/java/io/neonbee/internal/verticle/ServerVerticleTest.java

- rename ErrorHandler to DefaultErrorHandler
- remove create() pattern from the handler, because the
DefaultErrorHandler is a class and not an interface like the
ErrorHandler in Vert.x
- As in Vert.x an ErrorHandler interface already exists, reuse this
interface when implementing our own error handler.
- add errorHandler property to the ServerVerticleConfig

feat: add support for custom error handlers

---

docs/roadmap.md
resources/config/io.neonbee.internal.verticle.ServerVerticle.example.yaml
src/main/java/io/neonbee/endpoint/odatav4/ODataV4Endpoint.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/OlingoEndpointHandler.java
src/main/java/io/neonbee/endpoint/raw/RawEndpoint.java
src/main/java/io/neonbee/internal/RegexBlockList.java
src/test/java/io/neonbee/endpoint/odatav4/ODataV4EndpointTest.java
src/test/java/io/neonbee/endpoint/odatav4/internal/olingo/OlingoEndpointHandlerTest.java
src/test/java/io/neonbee/endpoint/raw/RawEndpointTest.java
src/test/java/io/neonbee/internal/RegexBlockListTest.java

This change introduces new properties exposedEntities for the
ODataV4Endpoint and exposedVerticles for the RawEndpoint. These settings
can be used to initialize a new RegexBlockList, which can be used to
limit the verticles / entities exposed from a given endpoint.

feat!: introduce exposedEntities/Verticles allow/block lists

---

src/main/java/io/neonbee/internal/deploy/NeonBeeModule.java
src/main/java/io/neonbee/internal/scanner/ClassPathScanner.java
src/test/java/io/neonbee/internal/deploy/NeonBeeModuleTest.java
src/test/java/io/neonbee/internal/scanner/ClassPathScannerTest.java

Normally there is exactly one MANIFEST.MF on the classpath, because when
parsing a NeonBee-Module a complete isolated classloader is used. But at
the end it doesn't matter how many MANIFEST.MF files are existing as
long as there is only one that contains the NeonBee-Module attributes.
Therefore this change adds more tolerance to the NeonBee-Module
validation.
This also helps in case that a third party library (like Dynatrace)
manipulates the classpath of every URLClassloader by adding own JARs.

feat: allow multiple MANIFST.MF files when parsing NeonBee-Module

---

src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/OlingoEndpointHandler.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/CountEntityCollectionProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/EntityProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/PrimitiveProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelper.java
src/test/java/io/neonbee/endpoint/odatav4/ODataV4EndpointTest.java

With this change a helper class will be introduced, which offers a
static method `forwardRequests` that maps an ODataRequest into an entity
request and sends it to the related entity verticles. Before, this logic
was included in most of the handlers.
Co-authored-by: Pascal Krause <pascal.krause@sap.com>

refactor(processor): extract common methods into helper

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/entity/EntityModelManager.java
src/main/java/io/neonbee/internal/deploy/NeonBeeModule.java
src/main/java/io/neonbee/internal/scanner/ClassPathScanner.java
src/main/java/io/neonbee/internal/scanner/DeployableScanner.java
src/main/java/io/neonbee/internal/scanner/HookScanner.java
src/test/java/io/neonbee/internal/deploy/NeonBeeModuleTest.java
src/test/java/io/neonbee/internal/scanner/ClassPathScannerTest.java
src/test/java/io/neonbee/internal/scanner/HookScannerTest.java

Followed by the the DeployableScanner and the HookScanner, resulting in unblocking NeonBeeModule, the EntityModelManager and the NeonBee bootstrap overall.
Nicer implementation of closing the NeonBeeModule's associated SelfFirstClassLoader and fixing a bug in the HookScanner, which previously ignored hooks in the manifest file.

refactor: made the ClassPathScanner non-blocking

---

gradle/codeCoverage.gradle
src/generated/java/io/neonbee/config/ServerConfigConverter.java
src/main/java/io/neonbee/config/ServerConfig.java
src/main/java/io/neonbee/internal/handler/DefaultErrorHandler.java
src/main/java/io/neonbee/internal/helper/BufferHelper.java
src/main/java/io/neonbee/internal/helper/FileSystemHelper.java
src/main/java/io/neonbee/internal/verticle/ServerVerticle.java
src/test/java/io/neonbee/internal/verticle/ServerVerticleTest.java

Before this change the JsonObject passed to the ServerVerticle was used to read the configuration for the custom error template to use. With this change the JsonObject was replaced by the ServerConfig object. In addition to a custom errorHandlerClassName a new errorHandlerTemplate property was added, which can be used to just specify a different (HTML) template to use in the DefaultErrorHandler.

refactor: move error handler configuration to ServerConfig class

---

.github/workflows/publish.yml

This change will add a section to the release notes with information on how to consume neonbee from maven central via maven and gradle.

ci(gh-actions): add maven central section in release body

---

gradle/codeCoverage.gradle
src/main/java/io/neonbee/job/JobVerticle.java
src/test/java/io/neonbee/job/JobVerticleTest.java

A periodic JobSchedule with an interval of 0 could result into an
endless loop when JobVerticle tries to calculate the next execution.

feat: add JobSchedule validation

---

resources/config/io.neonbee.internal.verticle.ServerVerticle.example.yaml
src/main/java/io/neonbee/config/ServerConfig.java
src/test/java/io/neonbee/config/ServerConfigTest.java

With this fix, the properties `errorHandler` and `errorTemplate`, which
can be configured in the ServerVerticle config, will be working again. A
regression in the ServerConfig caused that these properties are ignored.

fix: rephrase error handler properties in config

---

build.gradle

build(deps): Bump com.sap.cds:cds4j-core dependency to 1.22.1 (latest available version) to get rid of CVE in transitive dependency net.minidev:json-smart:2.3 CVE-2021-27568.

build(deps): bump com.sap.cds:cds4j-core from 1.19.0 to 1.22.1

---

gradle/codeCoverage.gradle

Bump jacoco tool version from 0.8.5 to 0.8.7. Furthermore as jacoco's
"reportsDir" property is deprecated it is now updated to
"reportsDirectory" as mentioned in the documentation (see [1]).
[1] https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:configuring_the_jacoco_plugin

chore: bump jacoco tool version and update deprecated config prop

---

build.gradle
src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/handler/ErrorHandler.java
src/main/java/io/neonbee/internal/handler/DefaultErrorHandler.java
src/main/java/io/neonbee/internal/helper/BufferHelper.java
src/main/java/io/neonbee/internal/verticle/ServerVerticle.java
src/test/java/io/neonbee/internal/handler/DefaultErrorHandlerTest.java
src/test/java/io/neonbee/internal/verticle/ServerVerticleTest.java

A class that implements the new ErrorHandler interface MUST have a
default constructor. Otherwise NeonBee can't instantiate the class
during bootstrap phase.
The purpose of the initialize method is to allow the execution of
blocking code.

feat: offer a new ErrorHandler which can be initialized asynchronously

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/NeonBeeOptions.java
src/test/java/io/neonbee/NeonBeeOptionsTest.java

By moving the MetricOptions to the NeonBeeOptions, we are able to change the MetricOptions in a LauncherPreProcessor.

feat: move MetricOptions to NeonBeeOptions

---

src/main/java/io/neonbee/data/DataVerticle.java
src/test/java/io/neonbee/data/DataVerticleTest.java

When defining a name space via annotation, it is automatically casted to
lower case. Now createQualifiedName follows the same rules by casting
passed name spaces automatically to lower case.

feat: make usage of createQualifiedName more resilient

---

build.gradle
docs/metrics.md
src/generated/java/io/neonbee/config/MicrometerRegistryConfigConverter.java
src/generated/java/io/neonbee/config/NeonBeeConfigConverter.java
src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/NeonBeeOptions.java
src/main/java/io/neonbee/config/MicrometerRegistryConfig.java
src/main/java/io/neonbee/config/NeonBeeConfig.java
src/main/java/io/neonbee/config/metrics/MicrometerRegistryLoader.java
src/main/java/io/neonbee/endpoint/metrics/MetricsEndpoint.java
src/main/java/io/neonbee/endpoint/metrics/NeonBeePrometheusMeterRegistry.java
src/main/java/io/neonbee/endpoint/metrics/PrometheusScrapingHandler.java
src/main/java/io/neonbee/internal/helper/ConfigHelper.java
src/test/java/io/neonbee/NeonBeeMockHelper.java
src/test/java/io/neonbee/NeonBeeOptionsTest.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/config/NeonBeeConfigTest.java
src/test/java/io/neonbee/endpoint/metrics/NeonBeeMetricsTest.java
src/test/java/io/neonbee/endpoint/metrics/PrometheusScrapingHandlerTest.java
src/test/java/io/neonbee/entity/EntityModelManagerTest.java
src/test/resources/io/neonbee/config/io.neonbee.NeonBee.json
src/test/resources/io/neonbee/endpoint/metrics/config/io.neonbee.internal.verticle.ServerVerticle.yaml

With this change the config parameter `micrometerRegistries` is
introduced which allows the user to specify a list of (full qualified) class
names, which must implement the `load()` method of the functional interface
`MicrometerRegistryLoader`. The load method must return a
`MeterRegistry`, which will be added to the micrometer registries by
NeonBee. The `PrometheusMeterRegistry` will be the default
registry, which is only available when the `MetricsEndpoint` is loaded.

feat: add custom micrometer registries via NeonBeeConfig

---

src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/expression/operators/StringFunctionMethodCallOperator.java
src/test/java/io/neonbee/test/endpoint/odata/ODataFilterTest.java
src/test/java/io/neonbee/test/endpoint/odata/ODataOrderTest.java
src/test/java/io/neonbee/test/endpoint/odata/ODataReadEntitiesTest.java
src/test/java/io/neonbee/test/endpoint/odata/verticle/TestService1EntityVerticle.java

This fixes the problem that if an entity attribute can contain null values, it was not possible to query this attribute with a query like contains(x,'y') or contains(x,'Y').

fix: null values queried with contains

---

.github/workflows/.auto-upgrade.json
.github/workflows/dependencies.yml

With the dependency upgrade workflow, bumping the version of vertx (and
in the future also other dependencies) will be automated.
The workflow checks every day at midnight if a new release version of
vertx is available. If it finds a new version, a pull request will be
created which updates the version in the `build.gradle`.

ci: automate dependency upgrade (of vertx)

---

src/main/java/io/neonbee/Launcher.java
src/main/java/io/neonbee/NeonBeeOptions.java
src/main/java/io/neonbee/NeonBeeProfile.java
src/test/java/io/neonbee/LauncherTest.java
src/test/java/io/neonbee/NeonBeeOptionsTest.java
src/test/java/io/neonbee/NeonBeeProfileTest.java

Allow to set null / an empty list as active profiles, which means that no profiles are to be deployed and NeonBee will start with the system verticles only.

fix: allow no active profile, make ALL the default

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/config/NeonBeeConfig.java
src/main/java/io/neonbee/internal/SelfFirstClassLoader.java
src/test/java/io/neonbee/config/NeonBeeConfigTest.java
src/test/java/io/neonbee/internal/SelfFirstClassLoaderTest.java

So far the SelfFirstClassLoader only allowed to specify parentPreferred className if the wildcard was at the end of the string like:
io.neonbee.*
If the wildcard was in any other position, the check failed. In additional the general implementation of the check was implemented inefficiently, because of a list traversal, on every check, which is, for modules, every class that is to be loaded.
This change improves the wildcard logic, by compiling a pattern on initialization of the SelfFirstClassLoader, also allowing more complex patterns like:
io.neonbee.*.TestClass

refactor: improve wildcard handling in SelfFirstClassLoader

---

src/test/java/io/neonbee/data/DataVerticleTest.java
src/test/java/io/neonbee/test/helper/DataResponseVerifier.java
src/test/java/io/neonbee/test/helper/EntityResponseVerifier.java

The methods returned a failed future, but should return a successful future.

fix: assertDataFailure should return a succeeded future

---

src/main/java/io/neonbee/Launcher.java
src/main/java/io/neonbee/LauncherPreProcessor.java
src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/config/NeonBeeConfig.java
src/main/java/io/neonbee/config/metrics/MicrometerRegistryLoader.java
src/main/java/io/neonbee/internal/helper/ConfigHelper.java
src/test/java/io/neonbee/NeonBeeMockHelper.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/config/NeonBeeConfigTest.java

Add a temporary Vert.x instance to load the NeonBeeConfig in the Launcher. This Vert.x instance is also passed to the new LauncherPreProcessor execute method. The MicrometerRegistryLoader has been modified accordingly to add the ability to pass a Vert.x instance to the load method.
see https://github.com/SAP/neonbee/issues/95

feat: add temporary vertx instance

---

build.gradle
resources/config/io.neonbee.NeonBee.yaml
src/generated/java/io/neonbee/config/HealthConfigConverter.java
src/generated/java/io/neonbee/config/NeonBeeConfigConverter.java
src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/config/HealthConfig.java
src/main/java/io/neonbee/config/NeonBeeConfig.java
src/main/java/io/neonbee/health/AbstractHealthCheck.java
src/main/java/io/neonbee/health/HazelcastClusterHealthCheck.java
src/main/java/io/neonbee/health/HealthCheckException.java
src/main/java/io/neonbee/health/HealthCheckRegistry.java
src/main/java/io/neonbee/health/MemoryHealthCheck.java
src/main/java/io/neonbee/health/internal/HealthCheck.java
src/main/java/io/neonbee/health/internal/MemoryStats.java
src/test/java/io/neonbee/NeonBeeMockHelper.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/config/NeonBeeConfigTest.java
src/test/java/io/neonbee/health/AbstractHealthCheckTest.java
src/test/java/io/neonbee/health/HazelcastClusterHealthCheckTest.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java
src/test/java/io/neonbee/health/MemoryHealthCheckTest.java

In order to provide a generic and extendable way of creating health
checks in NeonBee, a central registry is needed where health checks can
be provided. To achieve this, a `HealthCheckRegistry` is added to
NeonBee which will keep track of all default health checks of NeonBee
and custom health checks provided by the NeonBee user.
Vert.x already comes with a health check plugin which will be used for
the health check objects that can be registered on to the registry.
However, as the plugin does not prevent overriding of already existing
health check procedures, a wrapper is necessary to provide this
functionality. In addition, a caching mechanism is implemented which can
be controlled via the retention time. The retention time is the time
from the last health check until a new health check …

feat: add health checks

---

src/main/java/io/neonbee/health/AbstractHealthCheck.java
src/test/java/io/neonbee/health/AbstractHealthCheckTest.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java

This change ensures that reading the health check config file from the
config directory succeeds in case the file does not exist and returns
the default configuration otherwise.

fix(health): succeed if health check config not found

---

docs/metrics.md
src/generated/java/io/neonbee/config/MetricsConfigConverter.java
src/generated/java/io/neonbee/config/NeonBeeConfigConverter.java
src/main/java/io/neonbee/config/MetricsConfig.java
src/main/java/io/neonbee/config/NeonBeeConfig.java
src/main/java/io/neonbee/data/DataVerticle.java
src/main/java/io/neonbee/data/internal/metrics/ConfiguredDataVerticleMetrics.java
src/main/java/io/neonbee/data/internal/metrics/DataVerticleMetrics.java
src/main/java/io/neonbee/data/internal/metrics/DataVerticleMetricsImpl.java
src/main/java/io/neonbee/data/internal/metrics/NoopDataVerticleMetrics.java
src/test/java/io/neonbee/config/NeonBeeConfigTest.java
src/test/java/io/neonbee/data/DataVerticleTest.java
src/test/java/io/neonbee/data/internal/metrics/ConfiguredDataVerticleMetricsTest.java
src/test/java/io/neonbee/data/internal/metrics/DataVerticleMetricsImplTest.java
src/test/java/io/neonbee/data/internal/metrics/TestRequireDataVerticle.java
src/test/java/io/neonbee/data/internal/metrics/TestSourceDataVerticle.java

This feature adds metrics for the DataVertical methods requestData and retrieveData. Four metrics are implemented.
| metric | discription |
|---|---|
| Time metric | How long it takes to retrieve the data. |
| Status counter | How many requests completed successfully, how many requests failed |
| Number of requests | Total of all requests |
| Active requests | How many requests are currently open |
The metrics are disabled by default. You can enable the metrics for all DataVerticle by setting the NeonBeeConfig metrics.enabled value to true.
io.neonbee.NeonBee.yaml:
```yaml
metrics:
    enabled: true
```
The metrics can be also configured using the verticle configuration. To enable the metrics for a individual DataVerticle, it is necessary to add the config.metrics.enabled key with the …

feat: add metrics to DataVerticle

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/health/AbstractHealthCheck.java
src/main/java/io/neonbee/health/HazelcastClusterHealthCheck.java
src/main/java/io/neonbee/health/HealthCheckProvider.java
src/main/java/io/neonbee/health/MemoryHealthCheck.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/health/AbstractHealthCheckTest.java
src/test/java/io/neonbee/health/DummyHealthCheck.java
src/test/java/io/neonbee/health/DummyHealthCheckProvider.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java

Make health checks addable via SPI

---

src/test/java/io/neonbee/endpoint/metrics/NeonBeeMetricsTest.java

The test method NeonBeeMetricsTest#testCustomMetric occasionally takes more than a minute to execute. By setting setIgnoreClassPath to true, the test will execute in less than 15 seconds.

fix: speed up the test execution

---

docs/ServerVerticle.md
resources/config/io.neonbee.internal.verticle.ServerVerticle.example.yaml
src/generated/java/io/neonbee/config/ServerConfigConverter.java
src/main/java/io/neonbee/config/ServerConfig.java
src/main/java/io/neonbee/internal/handler/factories/CacheControlHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/CorrelationIdHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/DisallowingFileUploadBodyHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/InstanceInfoHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/LoggerHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/RoutingHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/SessionHandlerFactory.java
src/main/java/io/neonbee/internal/handler/factories/TimeoutHandlerFactory.java
src/main/java/io/neonbee/internal/verticle/ServerVerticle.java
src/test/java/io/neonbee/config/ServerConfigTest.java
src/test/java/io/neonbee/internal/handler/factories/CacheControlHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/CorrelationIdHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/DisallowingFileUploadBodyHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/InstanceInfoHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/LoggerHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/SessionHandlerFactoryTest.java
src/test/java/io/neonbee/internal/handler/factories/TimeoutHandlerFactoryTest.java
src/test/java/io/neonbee/internal/verticle/ServerVerticleTest.java

The `ServerVerticle` attaches request handlers to the route. The request handlers attached to the route cannot be changed at the moment. This change makes the request handlers that the `ServerVerticle` attaches to the route configurable.
A `RoutingHandlerFactory` is used to create an instance of the `Handler<RoutingContext>` class. In the `ServerConfig`, a list of `RoutingHandlerFactory` class names is used to specify the `RoutingHandlerFactory`. The handler created by the `RoutingHandlerFactory` is then added to the root route. The request handlers are added in the order specified in the `ServerConfig` list.

feat: Make ServerVerticle handler configurable.

---

src/main/java/io/neonbee/NeonBee.java

The random NeonBee NODE_ID is the same for all NeonBee instances loaded
from the same classloader. This fix makes the NeonBee nodeId an instance
variable so that each NeonBee instance has its own nodeId.

fix: same NeonBee nodeId for multiple instances

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/data/DataException.java
src/main/java/io/neonbee/data/DataVerticle.java
src/main/java/io/neonbee/internal/codec/DataExceptionMessageCodec.java
src/test/java/io/neonbee/cluster/DataExceptionRequestTest.java
src/test/java/io/neonbee/data/DataExceptionTest.java
src/test/java/io/neonbee/internal/codec/DataExceptionMessageCodecTest.java

Currently DataException only allows propagation of one error message. The intention is to add an failureDetail message to be able to propagate source error messages to the invoker, but should not be exposed to the consumer. A message codec for DataException is provided to allow serialization/deserialization of DataException objects via the event bus.

feat: extend DataException and return DataException via eventbus

---

build.gradle
src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/NeonBeeOptions.java
src/test/java/io/neonbee/LauncherTest.java
src/test/java/io/neonbee/NeonBeeExtension.java
src/test/java/io/neonbee/NeonBeeExtensionBasedTest.java
src/test/java/io/neonbee/NeonBeeMockHelper.java
src/test/java/io/neonbee/NeonBeeOptionsTest.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/test/helper/OptionsHelper.java

Tests based on NeonBeeExtension are very slow, because NeonBeeExtension always constructs a real
Hazelcast cluster. With this change NeonBeeExtension will use the Vert.x FakeClusterManager which
speed up these tests dramatically.

feat: use Vert.x FakeClusterManager in NeonBeeExtension

---

src/test/java/io/neonbee/NeonBeeExtension.java
src/test/java/io/neonbee/NeonBeeInstanceConfiguration.java

This change allows to choose the ClusterManager that will be used for the test execution. The default is the vert.x FakeClusterManager. You can choose other ClusterManagers by setting the testClusterManager value in the NeonBeeInstanceConfiguration annotation.

feat: make test cluster manager configurable.

---

src/main/java/io/neonbee/cluster/ClusterManagerFactory.java

When Infinispan is initialized it is using the ContextClassLoader of the current Thread to resolve resources. The ContextClassLoader of a Vert.x event loop is initially null, which causes Infinispan to fail.

fix: make SystemClassLoader available to Infinispan

---

src/main/java/io/neonbee/cluster/ClusterManagerFactory.java

When NeonBee is stated in clustered mode with Hazelcast as cluster manager, an IllegalArgumentException, "classLoader can't be null" is thrown.

fix: pass SystemClassLoader to cluster manager configuration

---

build.gradle
src/main/java/io/neonbee/NeonBee.java
src/test/java/io/neonbee/NeonBeeExtension.java
src/test/java/io/neonbee/NeonBeeExtensionBasedTest.java
src/test/java/io/neonbee/NeonBeeTest.java
src/test/java/io/neonbee/cluster/ClusterManagerFactoryTest.java
src/test/java/io/neonbee/cluster/DataExceptionRequestTest.java
src/test/java/io/neonbee/cluster/LocalPreferredClusterTest.java
src/test/java/io/neonbee/cluster/LocalRequestClusterTest.java
src/test/java/io/neonbee/cluster/TrackingInterceptorClusterTest.java
src/test/java/io/neonbee/endpoint/metrics/NeonBeeMetricsTest.java
src/test/java/io/neonbee/health/EventLoopHealthCheckTest.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java
src/test/java/io/neonbee/internal/logging/LoggerManagerVerticleClusterTest.java
src/test/java/io/neonbee/internal/verticle/HealthCheckVerticleTest.java
src/test/java/io/neonbee/test/base/NeonBeeTestBase.java
src/test/java/io/neonbee/test/listeners/StaleThreadChecker.java

- Re-enable parallel test execution (old issues are fixed)
- Better to reset the FakeClusterManager more often than not
- The Infinispan cluster manager must be stopped after tests
- A test with a timeout of over a hour is not good
- Tests that create own Vert.x instances or NeonBee(s) must take care to also shut them down properly, which can be very tricky. Generally it is recommended to use existing test bases or extensios, as they take care to properly shut down the instance(s).
- Tests that use the FakeClusterManager must run isolated
- Test methods that are in a NeonBeeTestBase, but not require NeonBee, can now be tagged with a @tag(DOESNT_REQUIRE_NEONBEE)
- Improve StaleThreadChecker to locate all tests creating stale threads (set VERBOSE = true, disable parallel execution and …

ci: fix tests

---

src/main/java/io/neonbee/endpoint/odatav4/ODataV4Endpoint.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelper.java
src/test/java/io/neonbee/test/endpoint/odata/ODataReadEntitiesTest.java

The OdataRequest RawQueryPath is expected to be in Percent-encoding, but it was decoded.

fix: odata query encoding

---

build.gradle

Contains Patches for two CVEs in `jackson-databind`:
- [CVE-2022-42003](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003)
- [CVE-2022-42004](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42004)

build(deps): upgrade `com.fasterxml.jackson` to 2.13.4

---

gradle/distribution.gradle

This PR adds a gradle task that generates a version file under `META-INF/neonbee` called `neonbee-version.txt`.
closes #198

Include version file inside jar under META-INF/neonbee

---

src/main/java/io/neonbee/data/DataQuery.java
src/main/java/io/neonbee/data/DataVerticle.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelper.java
src/main/java/io/neonbee/endpoint/raw/RawEndpoint.java
src/main/java/io/neonbee/entity/EntityVerticle.java
src/test/java/io/neonbee/data/DataQueryTest.java
src/test/java/io/neonbee/endpoint/raw/RawEndpointTest.java
src/test/java/io/neonbee/entity/EntityVerticleTest.java
src/test/java/io/neonbee/internal/codec/DataQueryMessageCodecTest.java
src/test/java/io/neonbee/test/endpoint/odata/ODataFilterTest.java

In this pull request two problems are fixed
1.  DataQuery cannot correctly process query strings
The DataQuery expects a decoded query string in the setQuery method and
in the constructors that accept a query parameter. These methods are
now deprecated since this cannot be fixed. A new method setRawQuery is
introduced which accepts the encoded query string and creates the
parameters from it.
3. odata query encoding in EntityVerticle
The parseUri method expects the query parameter to be in percent
encoding, but it was decoded.

fix: odata query encoding and DataQuery setQuery

---

src/main/java/io/neonbee/NeonBee.java
src/test/java/io/neonbee/NeonBeeTest.java

In case that HealthChecks are disabled by the config, there is no need to deploy the HealthCheckVerticle which is serving the results from the HealthChecks.

feat: deploy HealthCheckVerticle only if HealthChecks are enabled

---

src/test/java/io/neonbee/test/base/EntityVerticleTestBaseTest.java
src/test/java/io/neonbee/test/helper/DummyVerticleHelper.java

The EntityVerticle#getName returns the same name for each EntityVerticle created with the createDummyEntityVerticle method. Therefore, all created EntityVerticles are listing on the same event bus address and Vert.x is calling the EntityVerticles in a round-robin fashion.
To fix this, the getName method for the created EntityVerticle objects is overridden with Mockito#spy.

fix: getName for dummy EntityVerticle

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/entity/EntityVerticle.java
src/main/java/io/neonbee/health/HealthCheckRegistry.java
src/main/java/io/neonbee/internal/Registry.java
src/main/java/io/neonbee/internal/WriteSafeRegistry.java
src/main/java/io/neonbee/internal/verticle/HealthCheckVerticle.java
src/test/java/io/neonbee/entity/EntityVerticleTest.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java
src/test/java/io/neonbee/internal/WriteSafeRegistryTest.java
src/test/java/io/neonbee/internal/verticle/HealthCheckVerticleTest.java

There is a registry logic that is commonly used. In order to reuse this logic, I have moved this logic to a new WriteSafeRegistry class.

refactor: extract registry logic

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/hook/HookType.java
src/main/java/io/neonbee/internal/cluster/ClusterHelper.java
src/main/java/io/neonbee/internal/cluster/entity/ClusterEntityRegistry.java
src/main/java/io/neonbee/internal/cluster/entity/UnregisterEntityVerticlesHook.java
src/test/java/io/neonbee/hook/internal/DefaultHookRegistryTest.java
src/test/java/io/neonbee/internal/cluster/entity/ClusterEntityRegistryTest.java
src/test/java/io/neonbee/internal/cluster/entity/UnregisterEntitiesTest.java

NeonBee uses the shared map to manage the registration fo entities to
EntityVerticles e.g:
("Products" -> "ProductsVerticle")
("OrderTypes" -> "C4SOrderTypesVerticle")
During the boot up of an EntityVerticle "announceEntityVerticle" is used to register:
"Entity Products" is handled by "me" (EntityProductsVerticle)
Currently no "stop()" method is implemented, and no fallback handling was implemented (so the map may contain entries of verticles that no longer exist)
This commit adds two methods to delete the registered entities from the shared map.
The `UnregisterEntityModelHook#unregisterOnShutdown` method is executed if a node shuts down gracefully.
The `UnregisterEntityModelHook#cleanup` method is executed when the cluster detects that a node has left

feat: unregister entities from shared map

---

gradle/spotless/eclipse-formatter.xml

Never join lines that have already been wrapped.
Disabling the join_wrapped_lines formatting option allows the code to be formatted a bit more freely, but gives us the opportunity to make the code more readable. 
For example, the code below is quite confusing:
```
deployVerticle(firstCustomerEV).compose(x -> deployVerticle(financeEV)).compose(x -> requestEntity(CUSTOMER))
.onSuccess(entityWrapper -> context.verify(() -> {
// ...
})).compose(x -> requestEntity(CUSTOMER)).onSuccess(entityWrapper -> context.verify(() -> {
// ...
})).onFailure(context::failNow);
```
Now it is possible to write the code in a better structured way:
```
deployVerticle(firstCustomerEV)
.compose(x -> deployVerticle(financeEV))
.compose(x -> requestEntity(CUSTOMER))
.onSuccess(entityWrapper -> context.verify(() -> …
```

chore: Change spotless code formatter

---

src/main/java/io/neonbee/config/ServerConfig.java
src/main/java/io/neonbee/endpoint/health/HealthCheckHandler.java
src/main/java/io/neonbee/endpoint/health/HealthEndpoint.java
src/main/java/io/neonbee/endpoint/health/StatusEndpoint.java
src/main/java/io/neonbee/health/HealthCheckRegistry.java
src/test/java/io/neonbee/endpoint/health/HealthCheckHandlerTest.java
src/test/java/io/neonbee/endpoint/health/HealthEndpointTest.java
src/test/java/io/neonbee/endpoint/health/StatusEndpointTest.java
src/test/java/io/neonbee/health/HealthCheckRegistryTest.java

With this change a `StatusEndpoint` is introduced, which allows to display health onformation in a non-verbose way. This endpoint is meant to be public and usable for external system monitoring tools. The endpoint is mounted at /status and is part of the default endpoints of NeonBee. The /health endpoint will continue to serve health data in a verbose way, and it should be considered by the user to protect this endpoint as it might expose system information that should not be available to external parties.
In addition, the `HealthCheckHandler` is extended to support health check based filtering vie the request path of the /health endpoint.

feat(health): add status endpoint & support filtering

---

src/main/java/io/neonbee/NeonBeeOptions.java
src/main/java/io/neonbee/internal/handler/InstanceInfoHandler.java
src/test/java/io/neonbee/NeonBeeOptionsTest.java

For security reasons, the webserver name should not be public, because this allows attackers to gather information about the application and potentially identify new attack surfaces. The NeonBee prefix in the X-Instance-Info header does not provide any benefit, and therefore can be removed.
Closes #268

chore: remove webserver name from X-Instance-Info header

---

docs/usage/test/odata.md
src/test/java/io/neonbee/endpoint/odatav4/ODataV4EndpointTest.java
src/test/java/io/neonbee/endpoint/odatav4/internal/olingo/etag/ETagTest.java
src/test/java/io/neonbee/test/base/ODataMetadataRequest.java
src/test/java/io/neonbee/test/base/ODataMetadataRequestTest.java
src/test/java/io/neonbee/test/base/ODataRequest.java
src/test/java/io/neonbee/test/base/ODataRequestTest.java
src/test/java/io/neonbee/test/endpoint/odata/ODataReadEntityTest.java

Introduction of ODataMetadataRequest inheriting from AbstractODataRequest and replacing ODataRequest#setMetadata for a clearer API

refactor(odata): implement ODataMetadataRequest and deprecate ODataRequest#setMetadata

---

src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/CountEntityCollectionProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelper.java
src/test/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/ProcessorHelperTest.java
src/test/java/io/neonbee/test/endpoint/odata/verticle/ODataCountTest.java

This commit allows to pass the count information via response hint, which is a hugh performance benefit, because it is no longer necessary to send all entities back to the ODataEndpoint.

feat: allow to pass count value via response hints

---

src/main/java/io/neonbee/entity/EntityVerticle.java

When a request is made to a verticle which requests data from other verticles, which due to some issue are not registered in the shared map, it becomes difficult to understand for which entity type there is no verticle registered. Providing the FQN of the entity type in the error message, makes it easier to identify for which entity type there is no verticle registered.

chore: improve error message when no verticle is registered for an entity type

---

src/main/java/io/neonbee/data/DataVerticle.java
src/test/java/io/neonbee/data/internal/metrics/DataVerticleMetricsImplTest.java

dynatrace logs the following warning when a Tag with a null or empty value is added:
Warning: null or empty dimension value passed to normalization. To avoid this warning, an additional check if the value is empty is added.

fix: dynatrace null or empty dimension warning

---

build.gradle
src/main/java/io/neonbee/cache/BufferingDataVerticle.java
src/main/java/io/neonbee/cache/CachingDataVerticle.java
src/main/java/io/neonbee/hook/HookRegistration.java
src/test/java/io/neonbee/cache/BufferingDataVerticleTest.java
src/test/java/io/neonbee/cache/CachingDataVerticleTest.java

This change introduces a in-memory caching concept for DataVerticle, as well as an option to coalesce same requests sent to a verticle in parallel. The new CachingDataVerticle allows to define an arbitrary cacheKey that is used to store responses received by the DataVerticle in-memory. The next time data with the same cacheKey is requested, neither the required data verticles, nor the original requireData method is being invoked. Instead the data is returned straight from the in-memory cache. This also allows for request coalescing, meaning that if multiple requests are sent to the verticle with the same cacheKey at the same time, the verticle will only do one call to requestData and return the data straight from cache for the other request instead.

feat: introduce in-memory caching / request coalescing

---

src/test/java/io/neonbee/cache/BufferingDataVerticleTest.java
src/test/java/io/neonbee/cache/CachingDataVerticleTest.java
src/test/java/io/neonbee/endpoint/health/HealthEndpointTest.java
src/test/java/io/neonbee/endpoint/health/StatusEndpointTest.java

The timeouts for unit tests are controlled via the environment, see [1].
[1] https://github.com/SAP/neonbee/commit/02d22528

fix: removed Timout annotations

---

build.gradle

caffine is causing issues during the local development, as gradle is not able to resolve caffeine to a certain version

build(deps): exclude caffeine from vertx-infinispan

---

.github/workflows/codeql.yml

Fixes #356.
CodeQL will get triggered upon:
* Merge of pull requests to `main`.
* Pull requests introducting vulnerable code.
Notes:

feat: add a CodeQL Github Workflow

---

build.gradle

`resolutionStrategy` is only evaluated in the gradle build context. It is not evaluated by maven-publish. The versions are therefore missing in the generated POM file.
e.g.: https://repo1.maven.org/maven2/io/neonbee/neonbee-core/0.30.0/neonbee-core-0.30.0.pom

fix: overriding dependency target maven-publish

---

gradle/distribution.gradle

Currently, the automatic module name is resolved to `neonbee.core`. This commit changes the automatic module name to `io.neonbee.core`.

BREAKING CHANGE: set Automatic-Module-Name

---

src/main/java/io/neonbee/endpoint/Endpoint.java
src/main/java/io/neonbee/endpoint/raw/RawEndpoint.java
src/test/java/io/neonbee/endpoint/raw/RawEndpointTest.java

All HTTP headers from the `DataContext` response data `RESPONSE_HEADERS_HINT` are set in the HTTP response.

feat: allow to set HTTP response values

---

build.gradle
src/main/java/io/neonbee/endpoint/Endpoint.java
src/main/java/io/neonbee/endpoint/raw/RawEndpoint.java
src/test/java/io/neonbee/endpoint/raw/RawEndpointTest.java

feat: allow to set HTTP response values
All HTTP headers from the `DataContext` response data
`RESPONSE_HEADERS` are set in the HTTP response.

Feat/http response headers nb0.31

---

src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/expression/operands/ExpressionVisitorOperand.java
src/test/java/io/neonbee/test/endpoint/odata/ODataFilterEqNull.java

This commit resolves an error encountered when applying $filter with GUID values in an OData endpoint.

fix: odata guid type casting issue

---

src/main/java/io/neonbee/internal/handler/ChainAuthHandler.java

A problem with the ChainAuthHandler was introduced in vert.x version 4.5.6. To mitigate the issue, we do not use the vert.x ChainAuthHandler when only one AuthenticationHandler is used. The problem still exists when more than one AuthenticationHandler is used.
https://github.com/vert-x3/vertx-web/issues/2611

fix: mitigate problem with ChainAuthHandler

---

src/main/java/io/neonbee/internal/cluster/entity/ClusterEntityRegistry.java
src/test/java/io/neonbee/internal/cluster/entity/ClusterEntityRegistryTest.java

The following exception potentially breaks the hazelcast cluster and we need to restart the cluster + approuter.
```
java.lang.NullPointerException: Cannot invoke "io.vertx.core.json.JsonArray.copy()" because the return value of "java.util.Map.remove(Object)" is null,
at io.neonbee.internal.cluster.entity.ClusterEntityRegistry.lambda$unregisterNode$1(ClusterEntityRegistry.java:127),
```

fix: null check

---

src/main/java/io/neonbee/internal/cluster/entity/ClusterEntityRegistry.java
src/test/java/io/neonbee/internal/cluster/entity/UnregisterEntitiesTest.java
src/test/java/io/neonbee/internal/job/RedeployEntitiesJobTest.java

When the `unregisterNode` method is called for another NeonBee node, and the executing node has an `EntityVerticle` that was also registered by the other node, the `EntityVerticle` was incorrectly unregistered for the executing node. This fix ensures that the `EntityVerticle` remains registered for the executing node.

fix: entity unregister node

---

src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/AsynchronousProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/BatchProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/CountEntityCollectionProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/EntityProcessor.java
src/main/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/PrimitiveProcessor.java
src/test/java/io/neonbee/endpoint/odatav4/internal/olingo/processor/AsynchronousProcessorTest.java

fix: #565 batch requests issue

---

.github/workflows/codeql.yml

CodeQL Action major versions v1 and v2 have been deprecated. This updates all occurrences of CodeQL Action to v3 to ensure compatibility.
Reference: https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/

chore(codeql): update CodeQL Action to v3

---

src/main/java/io/neonbee/NeonBee.java
src/main/java/io/neonbee/entity/EntityModelManager.java

ThreadLocal variables should be explicitly cleaned up when no longer used to prevent memory leaks, especially in environments with thread pools.
- Called `remove()` on `THREAD_LOCAL_ODATA` to ensure proper cleanup.

fix: prevent potential memory leak

---

.github/workflows/voter.yml

This commit updates the GitHub Actions workflow to use `actions/cache@v4` instead of the deprecated `actions/cache@v2`. Failure was caused by GitHub's deprecation of v1/v2, effective December 5, 2024. See: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-break

fix(ci): update actions/cache to v4 to prevent deprecation issues
